---
- name: Install Fail2ban
  package:
    name: fail2ban
    state: present
  become: true

- name: Create local settings Fail2ban
  copy:
    src: "{{ jail_conf_path }}"
    dest: "{{ jail_conf_local_path }}"
    remote_src: yes
    owner: "{{ cfg_owner }}"
    group: "{{ cfg_group }}"
    mode: '0644'
  become: true

- name: Configurate Fail2ban 
  command: sed -i 's|#allowipv6 = auto|allowipv6 = auto|' {{ fail2ban_conf_path }} 
  become: true

- name: Configurate Fail2ban jails
  command: sed -i 's|{{ item.regexp }}|{{ item.line }}|' {{ jail_conf_local_path }}
  loop:
        - { regexp: '#ignoreip = 127.0.0.1/8 ::1', line: 'ignoreip = 127.0.0.1/8 ::1 {{ fail2ban_ignoreips | join(" ") }}' }
        - { regexp: 'bantime  = 10m', line: 'bantime  = 1y' }
        - { regexp: 'maxretry = 5', line: 'maxretry = 4' }
        - { regexp: 'action = %(action_)s', line: 'action = iptables' }        
  become: true

- name: Create user settings for SSH
  ansible.builtin.template:
    src: sshd.local.j2
    dest: "{{ jail_sshd_conf_local_path }}"
    owner: "{{ cfg_owner }}"
    group: "{{ cfg_group }}"
    mode: '0644'
  become: true

- name: Create log file for SSHD jail
  file:
    path: "{{ jail_sshd_log_path }}"
    state: touch
    mode: '0755'
  notify:
    - Restart Fail2ban
  become: true