---
- name: Install fail2ban
  package:
    name: fail2ban
    state: present
  become: true

- name: Create local settings fail2ban
  copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    remote_src: yes
  become: true

- name: Configurate fail2ban
  command: sed -i 's|{{ item.regexp }}|{{ item.line }}|' /etc/fail2ban/jail.local
  loop:
        - { regexp: '#ignoreip = 127.0.0.1/8 ::1', line: 'ignoreip = 127.0.0.1/8 ::1/ {{ my_ip }}' }
        - { regexp: 'bantime  = 10m', line: 'bantime  = 1y' }
        - { regexp: 'maxretry = 5', line: 'maxretry = 4' }
        - { regexp: 'action = %(action_)s', line: 'action = iptables' }
  become: true
  
- name: Create user settings for ssh
  copy:
    content: |
      [sshd]
      action = iptables[name=sshd]
      allowipv6 = auto
      backend = systemd
      enabled = true
      filter = sshd
      logpath = {{ sshd_jail_log_path }}
      port = {{ ssh_port_custom }}         
    dest: /etc/fail2ban/jail.d/sshd.local   
  become: true

- name: Create log file for sshd jail
  file:
    path: "{{ sshd_jail_log_path }}"
    state: touch
    mode: u+rwx,g+rx,o+rx
  notify:
    - Restart fail2ban
    - Start fail2ban-client 
  become: true