---
- name: Include determine SSH port
  import_tasks: ssh_port.yml

- name: Include SSHD configurate
  import_tasks: sshd.yml

- name: Include File2ban install
  import_tasks: file2ban.yml

- name: Include UFW install
  import_tasks: ufw.yml