---
- name: Include determine ssh port
  import_tasks: ssh_port.yml
  check_mode: false

- name: Include sshd configurate
  import_tasks: sshd.yml

- name: Include file2ban configurate
  import_tasks: file2ban.yml

- name: Include ufw configurate
  import_tasks: ufw.yml