---
- name: Include determine SSH port
  ansible.builtin.import_tasks: ssh_port.yml

- name: Include SSHD configurate
  ansible.builtin.import_tasks: sshd.yml

- name: Include File2ban install
  ansible.builtin.import_tasks: file2ban.yml

- name: Include UFW install
  ansible.builtin.import_tasks: ufw.yml