---
- name: Install ufw
  apt:
    name: ufw
    state: present
    update_cache: true
  become: true

- name: Allow connections to custom SSH port
  ufw:
    rule: allow
    port: "{{ ssh_port_custom }}"
    proto: tcp
  notify: Enable ufw
  become: true