---
- name: Install UFW
  apt:
    name: ufw
    state: present
  become: true

- name: Allow connections to custom SSH port
  ufw:
    rule: allow
    port: "{{ ssh_port_custom }}"
    proto: tcp
  notify: Enable UFW
  become: true