---
- name: Restart SSHD
  service:
    name: sshd
    state: restarted
  become: true

- name: Restart Fail2ban
  service:
    name: fail2ban
    enabled: true
    state: restarted
  become: true

- name: Enable UFW
  community.general.ufw:
    state: enabled
  become: true